### ISSUE TITLE
Use an SSL certificate

### ISSUE THREAD

**Issue by wbprice** [zchaudhry11/GameLogger-public#1]
Even though I'm not providing Steam credentials to this app directly, it would make me (the user) feel more confident about providing personal info if the site were protected with an SSL cert.

**Comment by zchaudhry11** [comment]
Thanks for checking out my project! I agree that SSL would improve the user experience by giving users a greater feeling of security. Unfortunately, I decided to host my app with Azure which does not support SSL unless you pay more for the (expensive) basic tier. Since I am not gaining any revenue from this app I wanted to keep the costs as low as possible.

As a workaround to Azure's limitation, I am now routing my traffic through Cloudflare and enforcing HTTPS which allows me to use SSL. I greatly appreciate the feedback since you are the first company to actually take the time to look at my work.
