### ISSUE TITLE
Unable to add game

### ISSUE THREAD

**Issue by wbprice** [zchaudhry11/GameLogger-public#2]
![screenshot from 2017-12-26 11-44-51](https://user-images.githubusercontent.com/2590422/34360810-42ac4886-ea32-11e7-97ad-912f4105e8d2.png)

After creating an account I tried to add a game to my backlog.  I got the error message "Could not update backog."

**Comment by zchaudhry11** [comment]
This issue was caused by the fact that I have not updated my game database in quite some time. Tiny Metal is a recent game that came out in 2017 so it did not exist in my database. Unfortunately, I had to re-write my scraper since HL2B updated their layout and they don't actually provide an API to get game information but I have finished doing so and updated my game database so it now contains new releases of the last year and as a result, Tiny Metal can now be added without any issues.

This does indicate an issue with the overall user experience however, since there should be a more specific error message. The UI and UX in general needs quite a bit of work and once I get more free time I hope to scrap a lot of it and replace it with a more intuitive setup.

Thanks again for taking the time to use my app and give me valuable feedback!
